# Generated by Django 5.2.5 on 2026-01-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('prospect', 'Fusion Prospect'), ('member', 'Fusion Member'), ('declined', 'Fusion Declined')], default='prospect', max_length=20)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lab_name', models.CharField(max_length=200)),
                ('person_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('has_mill', models.BooleanField(default=False)),
                ('dentists_requested', models.IntegerField(blank=True, default=0, null=True)),
                ('zip_protect_1', models.CharField(blank=True, max_length=20)),
                ('zip_protect_2', models.CharField(blank=True, max_length=20)),
                ('zip_protect_3', models.CharField(blank=True, max_length=20)),
                ('zip_protect_4', models.CharField(blank=True, max_length=20)),
                ('zip_protect_5', models.CharField(blank=True, max_length=20)),
                ('zip_protect_6', models.CharField(blank=True, max_length=20)),
                ('zip_protect_7', models.CharField(blank=True, max_length=20)),
                ('zip_protect_8', models.CharField(blank=True, max_length=20)),
                ('zip_protect_9', models.CharField(blank=True, max_length=20)),
                ('zip_protect_10', models.CharField(blank=True, max_length=20)),
                ('next_contact_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prospect',
                'verbose_name_plural': 'Prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='prospects.prospect')),
            ],
            options={
                'verbose_name': 'Prospect Note',
                'verbose_name_plural': 'Prospect Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('crown_bridge', 'Crown and Bridge'), ('denture', 'Denture'), ('full_service', 'Full Service')], max_length=50)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='prospects.prospect')),
            ],
            options={
                'verbose_name': 'Prospect Service Type',
                'verbose_name_plural': 'Prospect Service Types',
                'unique_together': {('prospect', 'service_type')},
            },
        ),
    ]
