# Generated by Django 5.2.5 on 2026-01-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prospect',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
