# Generated by Django 5.2.5 on 2026-01-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_prospect_email_prospect_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospect',
            name='zip_qty_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
