# Generated by Django 5.2.5 on 2026-01-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_prospect_zip_qty_1_prospect_zip_qty_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('prospect', 'Fusion Prospect'), ('member', 'Fusion Member'), ('declined', 'Fusion Declined'), ('corporate', 'Corporate Lab')], default='prospect', max_length=20),
        ),
    ]
