# Generated by Django 5.2.5 on 2026-01-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_add_corporate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='lab_user',
            field=models.OneToOneField(blank=True, help_text='Lab user account created for this prospect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospect_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
