# Generated by Django 5.2.5 on 2026-01-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_add_lab_user_to_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='ams_history',
            field=models.CharField(blank=True, choices=[('current_ams_ed', 'Current AMS Ed'), ('current_onevoice', 'Current OneVoice'), ('current_member', 'Current Member'), ('past_member', 'Past Member')], default='', max_length=20),
        ),
    ]
