# Generated by Django 5.2.5 on 2026-02-28 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0006_add_ams_history_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('prospect_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mailer',
                'verbose_name_plural': 'Mailers',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('prospect', 'Fusion Prospect'), ('member', 'Fusion Member'), ('declined', 'Fusion Declined'), ('corporate', 'Corporate Lab'), ('mailed', 'Mailed'), ('callback', 'Call Back'), ('sent_to_keith', 'Sent to Keith'), ('keith_closed', 'Keith Closed'), ('not_interested', 'Not Interested')], default='prospect', max_length=20),
        ),
        migrations.CreateModel(
            name='LeadReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(help_text='Person at the lab Keith should ask for', max_length=200)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('sms_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_referrals', to='prospects.prospect')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead Referral',
                'verbose_name_plural': 'Lead Referrals',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.AddField(
            model_name='prospect',
            name='mailer',
            field=models.ForeignKey(blank=True, help_text='Mailer batch this prospect was imported from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='prospects.mailer'),
        ),
    ]
