# Generated by Django 5.2.5 on 2026-03-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0007_mailer_alter_prospect_status_leadreferral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(choices=[('prospect', 'Fusion Prospect'), ('member', 'Fusion Member'), ('declined', 'Fusion Declined'), ('corporate', 'Corporate Lab'), ('mailed', 'Mailed'), ('callback', 'Call Back'), ('sent_to_keith', 'Sent to Keith'), ('keith_closed', 'Keith Closed'), ('not_interested', 'Not Interested'), ('left_voicemail', 'Left Voicemail')], default='prospect', max_length=25),
        ),
    ]
