# Generated by Django 5.2.5 on 2026-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0008_alter_prospect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='next_contact_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
