# Generated by Django 5.2.5 on 2026-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0010_prospectnote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='quickbooks_id',
            field=models.CharField(blank=True, default='', help_text='QuickBooks customer ID', max_length=50),
        ),
    ]
