# Generated by Django 5.2.5 on 2026-03-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0011_prospect_quickbooks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='fusion_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
