# Generated by Django 5.2.5 on 2025-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lab_profile_id',
            field=models.IntegerField(blank=True, help_text='Link to labprofile.labID in external database', null=True),
        ),
    ]
