# Generated by Django 5.2.5 on 2025-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0003_dentist_user_alter_dentist_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=0, help_text='User account credits'),
        ),
    ]
