# Generated by Django 5.2.5 on 2025-08-19 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0004_customuser_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Number of credits to purchase')),
                ('quality_type', models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium Quality')], default='economy', max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per credit at time of purchase', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this purchase', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the purchase')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_purchases', to='mgmt.dentist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Purchase',
                'verbose_name_plural': 'Credit Purchases',
                'ordering': ['-created_at'],
            },
        ),
    ]
