# Generated by Django 5.2.5 on 2025-08-19 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_creditpurchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('deduction', 'Deduction'), ('adjustment', 'Adjustment')], max_length=10)),
                ('amount', models.IntegerField(help_text='Credit amount (positive for addition, negative for deduction)')),
                ('reason', models.CharField(help_text='Reason for the transaction', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance_after', models.IntegerField(help_text="User's credit balance after this transaction")),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='mgmt.dentist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
