# Generated by Django 5.2.5 on 2025-08-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0006_credittransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='is_reversed',
            field=models.BooleanField(default=False, help_text='Whether this transaction has been reversed'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='Transaction that reversed this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_of', to='mgmt.credittransaction'),
        ),
    ]
