# Generated by Django 5.2.5 on 2025-08-20 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0007_credittransaction_is_reversed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dentist_uploads/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the file')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('downloaded', 'Downloaded')], default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='mgmt.dentist')),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files_downloaded', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(limit_choices_to={'user_type': 'lab'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Upload',
                'verbose_name_plural': 'File Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
