# Generated by Django 5.2.5 on 2025-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0008_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='credit_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium Quality')], default='economy', help_text='Type of credits', max_length=10),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='economy_balance_after',
            field=models.IntegerField(default=0, help_text='Economy credit balance after transaction'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='premium_balance_after',
            field=models.IntegerField(default=0, help_text='Premium credit balance after transaction'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='economy_credits',
            field=models.IntegerField(default=0, help_text='Economy credit balance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_credits',
            field=models.IntegerField(default=0, help_text='Premium credit balance'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='balance_after',
            field=models.IntegerField(help_text='DEPRECATED - Use economy_balance_after and premium_balance_after'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='credits',
            field=models.IntegerField(default=0, help_text='DEPRECATED - Use economy_credits and premium_credits instead'),
        ),
    ]
