# Generated by Django 5.2.5 on 2026-01-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0009_credittransaction_credit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lab_logo',
            field=models.ImageField(blank=True, help_text='Lab logo image', null=True, upload_to='lab_logos/'),
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='quantity',
            field=models.IntegerField(help_text='Number of crown credits to purchase'),
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per crown credit at time of purchase', max_digits=10),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.IntegerField(help_text='Crown credit amount (positive for addition, negative for deduction)'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='credit_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium Quality')], default='economy', help_text='Type of crown credits', max_length=10),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='economy_balance_after',
            field=models.IntegerField(default=0, help_text='Economy crown credit balance after transaction'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='premium_balance_after',
            field=models.IntegerField(default=0, help_text='Premium crown credit balance after transaction'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='economy_credits',
            field=models.IntegerField(default=0, help_text='Economy crown credit balance'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='premium_credits',
            field=models.IntegerField(default=0, help_text='Premium crown credit balance'),
        ),
    ]
