# Generated by Django 5.2.5 on 2026-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0010_customuser_lab_logo_alter_creditpurchase_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='quality_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('layered_zirconia', 'Layered Zirconia'), ('emax_monolithic', 'Emax Monolithic'), ('emax_layered', 'Emax Layered'), ('custom_abutment', 'Custom Abutment'), ('custom_abutment_layered', 'Custom Abutment with Layered Zirconia'), ('titanium_bar', 'Titanium Bar'), ('allonx_zirconia', 'All-on-X Zirconia non-Layered')], default='economy', max_length=30),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='credit_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('layered_zirconia', 'Layered Zirconia'), ('emax_monolithic', 'Emax Monolithic'), ('emax_layered', 'Emax Layered'), ('custom_abutment', 'Custom Abutment'), ('custom_abutment_layered', 'Custom Abutment with Layered Zirconia'), ('titanium_bar', 'Titanium Bar'), ('allonx_zirconia', 'All-on-X Zirconia non-Layered')], default='economy', help_text='Type of crown credits', max_length=30),
        ),
        migrations.AlterField(
            model_name='defaultpricelist',
            name='type',
            field=models.CharField(choices=[('economy', 'Economy'), ('layered_zirconia', 'Layered Zirconia'), ('emax_monolithic', 'Emax Monolithic'), ('emax_layered', 'Emax Layered'), ('custom_abutment', 'Custom Abutment'), ('custom_abutment_layered', 'Custom Abutment with Layered Zirconia'), ('titanium_bar', 'Titanium Bar'), ('allonx_zirconia', 'All-on-X Zirconia non-Layered')], default='economy', help_text='Price type', max_length=30),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('economy', 'Economy'), ('layered_zirconia', 'Layered Zirconia'), ('emax_monolithic', 'Emax Monolithic'), ('emax_layered', 'Emax Layered'), ('custom_abutment', 'Custom Abutment'), ('custom_abutment_layered', 'Custom Abutment with Layered Zirconia'), ('titanium_bar', 'Titanium Bar'), ('allonx_zirconia', 'All-on-X Zirconia non-Layered')], default='economy', help_text='Price type', max_length=30),
        ),
    ]
