# Generated by Django 5.2.5 on 2026-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0012_customuser_address_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpurchase',
            name='product_description',
            field=models.CharField(blank=True, help_text='Product description for premium crowns', max_length=100),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='product_description',
            field=models.CharField(blank=True, help_text='Product description for premium crowns', max_length=100),
        ),
        migrations.AddField(
            model_name='defaultpricelist',
            name='product_description',
            field=models.CharField(blank=True, help_text='Product description (e.g., Layered Zirconia, Emax Layered)', max_length=100),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='product_description',
            field=models.CharField(blank=True, help_text='Product description (e.g., Layered Zirconia, Emax Layered)', max_length=100),
        ),
        migrations.AlterField(
            model_name='creditpurchase',
            name='quality_type',
            field=models.CharField(choices=[('economy', 'Economy Crowns'), ('premium', 'Premium Crowns')], default='economy', max_length=10),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='credit_type',
            field=models.CharField(choices=[('economy', 'Economy Crowns'), ('premium', 'Premium Crowns')], default='economy', help_text='Type of crown credits', max_length=10),
        ),
        migrations.AlterField(
            model_name='defaultpricelist',
            name='type',
            field=models.CharField(choices=[('economy', 'Economy Crowns'), ('premium', 'Premium Crowns')], default='economy', help_text='Price type', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('economy', 'Economy Crowns'), ('premium', 'Premium Crowns')], default='economy', help_text='Price type', max_length=10),
        ),
    ]
