# Generated by Django 5.2.5 on 2026-01-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0013_creditpurchase_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpricelist',
            name='is_cod',
            field=models.BooleanField(default=False, help_text='Collect on Delivery - flat rate pricing'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='is_cod',
            field=models.BooleanField(default=False, help_text='Collect on Delivery - flat rate pricing'),
        ),
        migrations.AlterField(
            model_name='defaultpricelist',
            name='applied_after',
            field=models.IntegerField(default=0, help_text='Number of units after which this price applies'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='applied_after',
            field=models.IntegerField(default=0, help_text='Number of units after which this price applies'),
        ),
    ]
