# Generated by Django 5.2.5 on 2026-01-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0014_defaultpricelist_is_cod_pricelist_is_cod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpricelist',
            name='notes',
            field=models.CharField(blank=True, help_text='Additional notes or specifics for this price', max_length=200),
        ),
    ]
