# Generated by Django 5.2.5 on 2026-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0015_defaultpricelist_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=50),
        ),
    ]
