# Generated by Django 5.2.5 on 2026-01-30 14:48

from django.db import migrations, models
import re


def migrate_addresses(apps, schema_editor):
    """Parse existing address field and populate structured fields."""
    CustomUser = apps.get_model('mgmt', 'CustomUser')

    for user in CustomUser.objects.filter(user_type='lab'):
        if not user.address:
            continue

        # Normalize line breaks
        address = user.address.replace('\r\n', '\n').replace('\r', '\n')
        lines = [line.strip() for line in address.split('\n') if line.strip()]

        if len(lines) >= 2:
            # First line is street address
            user.street_address = lines[0]

            # Second line should be "city, state zip"
            city_state_zip = lines[1]

            # Try to parse "City, State ZIP" format
            # Pattern: city, state zip (where zip can be 5 or 9 digits)
            match = re.match(r'^(.+?),\s*(.+?)\s+(\d{5}(?:-\d{4})?)$', city_state_zip)
            if match:
                user.city = match.group(1).strip()
                user.state = match.group(2).strip()
                user.zip_code = match.group(3).strip()
            else:
                # Try without zip code: "City, State"
                match = re.match(r'^(.+?),\s*(.+)$', city_state_zip)
                if match:
                    user.city = match.group(1).strip()
                    user.state = match.group(2).strip()
                else:
                    # Just put it in city field
                    user.city = city_state_zip
        elif len(lines) == 1:
            # Single line - put in street address
            user.street_address = lines[0]

        user.save()


def reverse_migrate_addresses(apps, schema_editor):
    """Reverse: combine structured fields back into address field."""
    CustomUser = apps.get_model('mgmt', 'CustomUser')

    for user in CustomUser.objects.filter(user_type='lab'):
        parts = []
        if user.street_address:
            parts.append(user.street_address)

        city_state_zip = []
        if user.city:
            city_state_zip.append(user.city)
        if user.state:
            if city_state_zip:
                city_state_zip.append(', ')
            city_state_zip.append(user.state)
        if user.zip_code:
            city_state_zip.append(' ')
            city_state_zip.append(user.zip_code)

        if city_state_zip:
            parts.append(''.join(city_state_zip))

        user.address = '\n'.join(parts)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0017_add_zip_protection_fields'),
    ]

    operations = [
        # First add the new fields
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Zip code', max_length=20),
        ),
        # Then migrate the data
        migrations.RunPython(migrate_addresses, reverse_migrate_addresses),
        # Finally remove the old field
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
    ]
