# Generated by Django 5.2.5 on 2026-02-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0019_add_zipcode_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('lab', 'Lab'), ('dentist', 'Dentist'), ('caller', 'Caller')], default='dentist', max_length=10),
        ),
    ]
