# Generated by Django 5.2.5 on 2026-03-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0020_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='script_file',
            field=models.FileField(blank=True, help_text='Optional prescription/script document to accompany the case file', null=True, upload_to='dentist_uploads/scripts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='script_original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
