# Generated by Django 5.2.5 on 2026-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0021_fileupload_script_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpurchase',
            name='quality_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium')], default='economy', max_length=10),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='credit_type',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium')], default='economy', help_text='Type of crown credits', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('lab', 'Lab'), ('dentist', 'Dentist'), ('caller', 'Caller'), ('superadmin', 'Super Admin'), ('ov_admin', 'OV Admin'), ('csr', 'CSR'), ('designer', 'Designer'), ('ov_client', 'OV Client')], default='dentist', max_length=10),
        ),
        migrations.AlterField(
            model_name='defaultpricelist',
            name='type',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium')], default='economy', help_text='Price type', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='type',
            field=models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium')], default='economy', help_text='Price type', max_length=10),
        ),
    ]
