# Generated by Django 5.2.5 on 2026-03-27 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0022_alter_creditpurchase_quality_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('lab', 'Lab'), ('dentist', 'Dentist'), ('caller', 'Caller'), ('superadmin', 'Super Admin'), ('ov_admin', 'OV Admin'), ('csr', 'CSR'), ('designer', 'Designer'), ('ov_client', 'OV Client')], max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary role for login routing and display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
