# Generated by Django 5.2.5 on 2026-03-27 12:08

from django.db import migrations


def populate_roles(apps, schema_editor):
    """Copy each user's user_type into a UserRole row with is_primary=True."""
    CustomUser = apps.get_model('mgmt', 'CustomUser')
    UserRole = apps.get_model('mgmt', 'UserRole')

    for user in CustomUser.objects.all():
        if user.user_type:
            UserRole.objects.get_or_create(
                user=user,
                role=user.user_type,
                defaults={'is_primary': True},
            )


def reverse_roles(apps, schema_editor):
    """Reverse: delete all UserRole rows (user_type field still has the data)."""
    UserRole = apps.get_model('mgmt', 'UserRole')
    UserRole.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0023_add_userrole_model'),
    ]

    operations = [
        migrations.RunPython(populate_roles, reverse_roles),
    ]
