# Generated by Django 5.2.5 on 2026-03-27 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0024_populate_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpricelist',
            name='lab',
            field=models.ForeignKey(limit_choices_to={'roles__role': 'lab'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='lab',
            field=models.ForeignKey(limit_choices_to={'roles__role': 'lab'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_dentists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional: Link to a user account for this dentist', limit_choices_to={'roles__role': 'dentist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='lab',
            field=models.ForeignKey(limit_choices_to={'roles__role': 'lab'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
