# Generated by Django 5.2.5 on 2026-04-07 15:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0025_update_limit_choices_to_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='mgmt.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Download',
                'verbose_name_plural': 'File Downloads',
                'ordering': ['-downloaded_at'],
                'unique_together': {('file_upload', 'user')},
            },
        ),
    ]
