"""
Django settings for fusion project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v%5(kxa49m1tp4d96-xufy9dhq40_vk!^7+%e$ur#a)nklr(wf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.amsfusion.com', 'amsfusion.com', 'prospects.amsfusion.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mgmt',
    'prospects',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fusion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fusion.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'fusion',
        'USER': 'fusion',
        'PASSWORD': 'Fjn32lGOo932JFJJASFlkjdfs',
        'HOST': 'localhost',
        'PORT': '3306'
    },
    'labprofile': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dentallabprofile',
        'USER': 'americasmiles',
        'PASSWORD': 'smiles2003',
        'HOST': '172.31.18.214',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/var/www/fusion/static'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/fusion/media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File Upload Settings
# Maximum size for file uploads (500MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024  # 500MB

# Custom User Model
AUTH_USER_MODEL = 'mgmt.CustomUser'

# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/prices/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'mgmt.backends.LabProfileBackend',  # Custom lab authentication
    'django.contrib.auth.backends.ModelBackend',  # Default Django authentication
]

# Email Configuration
# For Rackspace: secure.emailsrvr.com, port 587 (TLS) or 465 (SSL)
# For Gmail, use: smtp.gmail.com, port 587
# For SendGrid, use: smtp.sendgrid.net, port 587
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'secure.emailsrvr.com'  # Rackspace email server
EMAIL_PORT = 587  # Using TLS port
EMAIL_USE_TLS = True  # Enable TLS
EMAIL_USE_SSL = False  # Don't use SSL when using TLS
EMAIL_HOST_USER = 'info@amsfusion.com'  # Your email address
EMAIL_HOST_PASSWORD = 'asdf FDSA23t2AGFA'  # Your email password
DEFAULT_FROM_EMAIL = 'AMS Fusion <info@amsfusion.com>'
SERVER_EMAIL = 'AMS Fusion <info@amsfusion.com>'

# For development/testing, uncomment this to print emails to console instead
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Site URL for email links (update with your actual domain)
SITE_URL = 'http://your-domain.com'  # Change to https://yourdomain.com in production
