# Generated by Django 5.2.5 on 2026-03-25 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OVClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('onevoice', 'One Voice'), ('geofencing', 'Fusion Geofencing')], default='onevoice', max_length=20)),
                ('lab_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('membership_tier', models.CharField(choices=[('onevoice_295', 'One Voice $295/mo'), ('fusion_addon', 'Fusion with One Voice Add-on')], default='onevoice_295', max_length=20)),
                ('call_session_mode', models.IntegerField(choices=[(1, 'Mode 1 — Full Session'), (2, 'Mode 2 — One Appointment at a Time')], default=1)),
                ('mailing_list_size', models.IntegerField(default=100, help_text='Included dentists in monthly fee')),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='onboarding', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Visible to Admin and Super-Admin only')),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_csrs', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'csr'}, related_name='ov_assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'user_type': 'ov_client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ov_client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'One Voice Client',
                'ordering': ['lab_name'],
            },
        ),
        migrations.CreateModel(
            name='OVCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ov_call_sessions', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='onevoice.ovclient')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='OVBillingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('active_list_size', models.IntegerField()),
                ('included_size', models.IntegerField(help_text='From client mailing_list_size')),
                ('overage_count', models.IntegerField(default=0)),
                ('overage_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('overage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_snapshots', to='onevoice.ovclient')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='OVAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_text', models.TextField(help_text='Full agreement text at time of signing')),
                ('signature_name', models.CharField(blank=True, max_length=200)),
                ('signature_date', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ov_agreements_sent', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='onevoice.ovclient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OVClientAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_type', models.CharField(choices=[('recurring', 'Recurring Weekly'), ('specific', 'Specific Date')], max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='onevoice.ovclient')),
            ],
            options={
                'verbose_name_plural': 'Client availabilities',
            },
        ),
        migrations.CreateModel(
            name='OVDentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('practice_name', models.CharField(blank=True, max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('office_manager', models.CharField(blank=True, max_length=200)),
                ('specialty', models.CharField(choices=[('gp', 'General Practice'), ('prostho', 'Prosthodontist'), ('endo', 'Endodontist'), ('ortho', 'Orthodontist'), ('oralsurg', 'Oral Surgeon'), ('perio', 'Periodontist'), ('pedo', 'Pediatric Dentist'), ('other', 'Other')], default='gp', max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('never_called', 'Never Called'), ('no_answer', 'No Answer'), ('email_captured', 'Email Captured'), ('called_no_email', 'Called / No Email'), ('appointment', 'Appointment Booked'), ('do_not_contact', 'Do Not Contact'), ('removed', 'Removed')], default='never_called', max_length=20)),
                ('callback_flag', models.BooleanField(default=False)),
                ('callback_date', models.DateField(blank=True, null=True)),
                ('callback_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('correction_requested', models.BooleanField(default=False)),
                ('correction_notes', models.TextField(blank=True)),
                ('removal_flagged', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_csr', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'csr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ov_assigned_dentists', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentists', to='onevoice.ovclient')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ov_locked_dentists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OVCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('no_answer', 'No Answer'), ('voicemail', 'Left Voicemail'), ('spoke_not_interested', 'Spoke — Not Interested'), ('spoke_callback', 'Spoke — Call Back Later'), ('spoke_email_captured', 'Spoke — Email Captured'), ('spoke_appointment', 'Spoke — Appointment Booked'), ('wrong_number', 'Wrong Number'), ('disconnected', 'Disconnected'), ('out_of_business', 'Out of Business'), ('address_changed', 'Address Changed'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('email_captured', models.EmailField(blank=True, max_length=254)),
                ('callback_date', models.DateField(blank=True, null=True)),
                ('callback_time', models.TimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('csr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ov_call_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_records', to='onevoice.ovcallsession')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='onevoice.ovdentist')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='OVDentistStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='onevoice.ovdentist')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='OVListImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('filtered_count', models.IntegerField(default=0, help_text='Removed by specialty filter')),
                ('duplicate_count', models.IntegerField(default=0)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_imports', to='onevoice.ovclient')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='ovdentist',
            name='list_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dentists', to='onevoice.ovlistimport'),
        ),
        migrations.CreateModel(
            name='OVNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('welcome', 'Client Onboarded'), ('agreement_sent', 'Agreement Sent'), ('list_ready', 'List Ready'), ('appointment_booked', 'Appointment Booked'), ('appointment_passed', 'Appointment Passed'), ('appointment_reminder', 'Appointment Reminder'), ('followup_reminder', 'Follow-up Reminder'), ('session_done', 'CSR Session Done'), ('session_started', 'Call Session Started'), ('inventory_low', 'Inventory Low'), ('correction_request', 'Correction Request'), ('removal_request', 'Removal Request')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onevoice.ovclient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ov_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OVPostcardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='onevoice/postcard_templates/')),
                ('is_master_template', models.BooleanField(default=False, help_text='Part of the design library')),
                ('customized_image', models.ImageField(blank=True, null=True, upload_to='onevoice/postcard_customized/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Client Approval'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('approved_by_client', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postcard_designs', to='onevoice.ovclient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OVPostcardComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='onevoice.ovpostcarddesign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OVMailingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_schedule', to='onevoice.ovclient')),
                ('postcard_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onevoice.ovpostcarddesign')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='OVPostcardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('reorder_threshold', models.IntegerField(default=50)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='onevoice.ovclient')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='onevoice.ovpostcarddesign')),
            ],
            options={
                'verbose_name_plural': 'Postcard inventories',
            },
        ),
        migrations.CreateModel(
            name='OVPrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('mail_date', models.DateField(blank=True, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to='onevoice.ovclient')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onevoice.ovpostcarddesign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OVAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('case_status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('not_yet', 'Not Yet'), ('lost', 'Lost')], default='pending', max_length=20)),
                ('client_notes', models.TextField(blank=True)),
                ('followup_date', models.DateField(blank=True, help_text='Auto-set to 1 week after appointment', null=True)),
                ('followup_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ov_booked_appointments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='onevoice.ovclient')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='onevoice.ovdentist')),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
                'constraints': [models.UniqueConstraint(fields=('client', 'appointment_date', 'appointment_time'), name='unique_client_appointment_slot')],
            },
        ),
    ]
