# Generated by Django 5.2.5 on 2026-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onevoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovcallrecord',
            name='outcome',
            field=models.CharField(choices=[('confirmed_active', 'Confirmed Active'), ('no_answer', 'No Answer'), ('spoke_callback', 'Callback'), ('spoke_email_captured', 'Email Captured'), ('spoke_appointment', 'Appointment Booked'), ('do_not_contact', 'Do Not Contact'), ('out_of_business', 'Out of Business'), ('address_changed', 'Address Changed'), ('voicemail', 'Left Voicemail'), ('spoke_not_interested', 'Not Interested'), ('wrong_number', 'Wrong Number'), ('disconnected', 'Disconnected'), ('other', 'Other')], max_length=30),
        ),
    ]
