# Generated by Django 5.2.5 on 2026-03-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onevoice', '0002_alter_ovcallrecord_outcome'),
        ('prospects', '0010_prospectnote_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ovclient',
            name='prospect',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ov_client', to='prospects.prospect'),
        ),
    ]
