# Generated by Django 5.2.5 on 2026-03-27 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onevoice', '0003_ovclient_prospect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ovclient',
            name='assigned_csrs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'roles__role': 'csr'}, related_name='ov_assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ovclient',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'roles__role': 'ov_client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ov_client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ovdentist',
            name='assigned_csr',
            field=models.ForeignKey(blank=True, limit_choices_to={'roles__role': 'csr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ov_assigned_dentists', to=settings.AUTH_USER_MODEL),
        ),
    ]
